# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='header.proto',
  package='',
  serialized_pb='\n\x0cheader.proto\"a\n\x0eProtocolHeader\x12&\n\x05\x63mdid\x18\x01 \x02(\x0e\x32\x17.ProtocolHeader.Command\x12\x0f\n\x07\x64\x61talen\x18\x02 \x02(\x05\"\x16\n\x07\x43ommand\x12\x0b\n\x07REQUEST\x10\x01')



_PROTOCOLHEADER_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='ProtocolHeader.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=91,
  serialized_end=113,
)


_PROTOCOLHEADER = _descriptor.Descriptor(
  name='ProtocolHeader',
  full_name='ProtocolHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdid', full_name='ProtocolHeader.cmdid', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datalen', full_name='ProtocolHeader.datalen', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTOCOLHEADER_COMMAND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=113,
)

_PROTOCOLHEADER.fields_by_name['cmdid'].enum_type = _PROTOCOLHEADER_COMMAND
_PROTOCOLHEADER_COMMAND.containing_type = _PROTOCOLHEADER;
DESCRIPTOR.message_types_by_name['ProtocolHeader'] = _PROTOCOLHEADER

class ProtocolHeader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLHEADER

  # @@protoc_insertion_point(class_scope:ProtocolHeader)


# @@protoc_insertion_point(module_scope)
