# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_ack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_ack.proto',
  package='',
  serialized_pb='\n\x11message_ack.proto\"\x1d\n\x0ePushMessageAck\x12\x0b\n\x03ids\x18\x01 \x02(\t')




_PUSHMESSAGEACK = _descriptor.Descriptor(
  name='PushMessageAck',
  full_name='PushMessageAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='PushMessageAck.ids', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['PushMessageAck'] = _PUSHMESSAGEACK

class PushMessageAck(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PUSHMESSAGEACK

  # @@protoc_insertion_point(class_scope:PushMessageAck)


# @@protoc_insertion_point(module_scope)
